### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by FelixBrito** [NUKnightLab/juxtapose#104]
We're using images downloaded from our private ThinkStock account to create frame comparison for our online courses (to be delivered to our students via an LMS). Once Juxtapose creates the iframe using those images, will the frame comparison become public? Will everyone be able to see and use it even if they are not registered in our courses? Will we have issues with making public images that we bought from a stock imagery service?

**Comment by mprove** [comment]
no – the images can only be viewed from the page where the iframe is placed. As far as I understand Juxtapose will internally store only the URLs of your images. They are not shared otherwise.

**Comment by FelixBrito** [comment]
Thank you for following up.

Best regards,

Felix

Felix Brito
Director, Course Design and Production
Instructional Design and Development Department
Embry-Riddle Aeronautical University – Worldwide
600 S. Clyde Morris Blvd.
Daytona Beach, FL 32114
Email: debritoj@erau.edu
Office: 386 226 6962

From: mprove
Reply-To: NUKnightLab/juxtapose
Date: Friday, December 16, 2016 at 3:47 AM
To: NUKnightLab/juxtapose
Cc: Felix Brito, Author
Subject: Re: [NUKnightLab/juxtapose] Copyright issues (#104)


no – the images can only be viewed from the page where the iframe is placed. As far as I understand Juxtapose will internally store only the URLs of your images. They are not shared otherwise.
