### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by mprove** [NUKnightLab/juxtapose#108]
The License of this github project says: Mozilla Public License Version 2.0
juxtapose.js says: Copyright (c) 2015 Alex Duner and Northwestern University Knight Lab

I am confused. Which one is valid? Am I allowed to implement personal changes?

**Comment by JoeGermuska** [comment]
Software licenses and copyright do not fundamentally conflict. The copyright holder has the right to license his/her/its work, and we offer JuxtaposeJS under the [MPL 2.0](https://www.mozilla.org/en-US/MPL/2.0/).  The formal details of your responsibilities are in [section 3](https://www.mozilla.org/en-US/MPL/2.0/#responsibilities).

This text, from [Timeline's license page](http://timeline.knightlab.com/docs/license.html), applies to Juxtapose as well:

> TimelineJS is released under the [Mozilla Public License (MPL), version 2.0](Mozilla Public License (MPL), version 2.0). That means that TimelineJS is free to "use, reproduce, make available, modify, display, perform, distribute" or otherwise employ. You don't need our permission to publish stories with TimelineJS and you don't need to pay us any fees or arrange any further license beyond the MPL. You may also make changes to [our source code](https://github.com/NUKnightLab/TimelineJS3), although if you use changed code publicly, [you must make the source code to your modified version available.](https://www.mozilla.org/en-US/MPL/2.0/#distribution-of-source-form)
>
>Note that this page is not offered as legal counsel and you may wish to consult your own lawyers.
>
>If you have more questions, feel free to [reach out to us](http://knightlab.zendesk.com/).

Hopefully this clears things up. Basically, we would love to see people extend our work.

**Comment by mprove** [comment]
Thanks for your response.
