### ISSUE TITLE
Tips and Tricks needs written for orangeline update

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/juxtapose#109]
We have placeholder text for tips and tricks on the orangeline version of the juxtapose website.

**Comment by zachwise** [comment]
@JoeGermuska maybe you and I can come up with a few?

**Comment by JoeGermuska** [comment]
Suggestions:
* Use images that are the same size
* Export your images to web quality to improve download time

lemme know if you'd rather just do this f2f

**Comment by zachwise** [comment]
I would add "try to align your images so that major elements are in alignment."

**Comment by scott2b** [comment]
Please also remove the "Technical Documentation" section as it is all links to StoryMap docs
