### ISSUE TITLE
Does juxtapose support IE <= 8?

### ISSUE THREAD

**Issue by pallxk** [NUKnightLab/juxtapose#113]
(I was testing using https://github.com/NUKnightLab/juxtapose/blob/master/examples/example.html)

When I tested juxtapose, I found it did not work on IE <= 8. For example,

* on IE <= 8

  ```
  SCRIPT438: Object doesn't support property or method 'removeEventListener'
  ```

  is reported on the [line](https://github.com/NUKnightLab/juxtapose/blob/5edbd9defd86eff351efdce8dfb57b43fc07c688/juxtapose/js/juxtapose.js#L549):

  ```
  this.removeEventListener('mouseup', arguments.callee);
  ```

* on IE <= 7

  ```
  SCRIPT438: Object doesn't support property or method 'querySelectorAll'
  ```

  is reported on the [line](https://github.com/NUKnightLab/juxtapose/blob/5edbd9defd86eff351efdce8dfb57b43fc07c688/juxtapose/js/juxtapose.js#L685)

  ```
  var elements = document.querySelectorAll('.juxtapose');
  ```

while there is an addEventListener polyfill in the source code. So I'm not sure which version of IE can I expect for support?

By the way, on IE <= 9,

```
SCRIPT5: Access is denied.
```

is reportd on the [line](https://github.com/NUKnightLab/juxtapose/blob/5edbd9defd86eff351efdce8dfb57b43fc07c688/juxtapose/js/juxtapose.js#L65) when using flickr url.

```
request.open('GET', url, true);
```

**Comment by JoeGermuska** [comment]
IE8 is close to zero usage on recent stats I've looked at, but I also just merged some legacy code (#103) that has fixes for IE8. We don't have a reliable way to test on IE8, so I made sure it had no negative impact on current browsers. If you'd like to check it out, we welcome that.

While we haven't set formal browser support, generally, we are not equipped to expend a lot of energy maintaining long backwards compatibility. We'll work with our community who have an interest in that as best we can, but we'll be looking for contributions for anything other than current and one-most-recent versions of browsers.
