### ISSUE TITLE
Stray underscore in checkbox labels

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/juxtapose#118]
![image](https://cloud.githubusercontent.com/assets/46313/23956386/85c882fa-096a-11e7-8827-d9b88b89ec26.png)

**Comment by zachwise** [comment]
It's the leftover help button tooltips from the old design. We don't have an equivalent in orangeline. We should probably just comment that code out for now.

**Comment by scott2b** [comment]
commented
