### ISSUE TITLE
WordPress issues...!!!

### ISSUE THREAD

**Issue by Suleman-Elahi** [NUKnightLab/juxtapose#135]
The embed code disappears after saving the page. And I read somewhere that WordPress doesn't allow to add Iframes and other scripts. Is there any other way to use it on WordPress. Thanks in advance.

**Comment by JoeGermuska** [comment]
If you are asking about Wordpress.com, the answer is no. [iframes are not supported](https://en.support.wordpress.com/code/#flash-and-other-embeds) and they have not chosen to configure Wordpress.com to use our oembed service.

If you are using self-hosted WordPress, then we recommend installing the `iframe` plugin; you'll need to make minor edits to the embed code as it appears on the Juxtapose webpage, but hopefully those steps are clear from the iframe plugin documentation.  You could also look at the [Storytelling Tools plugin](https://wordpress.org/plugins/storytelling-tools/) created by INN, which makes it easier to use all of our tools in self-hosted WordPress.

For general reference, we prefer to receive questions like this in our support system, knightlab.zendesk.com
