### ISSUE TITLE
labCredit cross-origin links unsafe

### ISSUE THREAD

**Issue by matbrady** [NUKnightLab/juxtapose#158]
### Problem

[Google Lighthouse](https://developers.google.com/web/tools/lighthouse/) audits flag the `labCredit` link as being unsafe. This effects both performance and security. Details can be found [here](https://developers.google.com/web/tools/lighthouse/audits/noopener).

#### Example
The error can be seen on the [Boston Globe site](https://www.bostonglobe.com/metro/2014/10/23/returning-jackie-kennedy-vision/t7TCSfcdkjcQNBBkdbuvEO/story.html). 

<img width="600" alt="Screenshot 2019-09-11 10 54 02" src="https://user-images.githubusercontent.com/1770862/64708546-c35d0100-d482-11e9-8f0d-1f32d8fb924d.png">

[Report JSON Export](https://github.com/NUKnightLab/juxtapose/files/3601413/www.bostonglobe.com_2019-09-11_10-54-43.json.zip). 
Viewable here: https://googlechrome.github.io/lighthouse/viewer/
[Lighthouse Report.pdf](https://github.com/NUKnightLab/juxtapose/files/3601404/Lighthouse.Report.pdf)

### Proposed Solution

1. Update links to use `https` instead of `http`
1. Add `rel` attribute with a `noopener` value

**Comment by hoopyfrood** [comment]
+1, this would be a simple and great addition
