### ISSUE TITLE
Juxtapose embed not displaying on Safari on iOS

### ISSUE THREAD

**Issue by MPatton157** [NUKnightLab/juxtapose#181]
I've embedded a Juxtapose iframe into my Wordpress article. It displays perfectly fine on all web browsers on my PC, but doesn't display at all on my IPhone10 on Safari. There is simply a blank space in the article equal in height to the Juxtapose. Is there any way to fix this? Javascript is enabled on Safari on the phone

**Comment by JoeGermuska** [comment]
Can you provide a link to a page which demonstrates the issue?

I just created the simplest possible test case of opening a page with a Juxtapose iframe embed on iOS Safari, and it basically works. (For what it's worth, the demonstration slider on juxtapose.knightlab.com is not embedded with an iframe, so it is not a suitable test.)

So, for us to provide any further analysis, we will need a test case.

**Comment by MPatton157** [comment]
Somehow, the issue has resolved itself. I don’t know what caused it in the first place, or how it was fixed. I spent a while testing it on different phones, tinkering with the iframe, and just generally messing with things to avail, but when returning to the page this morning, it worked without issue. I have no idea how this happened.

Thank you for your response though, I appreciate it.

**Comment by JoeGermuska** [comment]
glad it's resolved!
