### ISSUE TITLE
Make Juxtapose work with iFrames

### ISSUE THREAD

**Issue by duner** [NUKnightLab/juxtapose#38]
Instead of copying the html and script tags, make Juxtapose easier to embed with iFrames.

**Comment by mihi-tr** [comment]
This seems to work quite well now...

**Comment by JoeGermuska** [comment]
@mihi-tr thanks for the feedback. this issue probably should be closed by now!  We're wrestling a little with implementation details -- we will soon be setting the width and height of the iframe for users who don't realize they need to (see #54)
