### ISSUE TITLE
Consider loading CSS from Javascript

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/juxtapose#42]
From Zendesk tickets, it seems like a lot of people are snagged by CMSes like Wordpress stripping the <link> tag that inlines the CSS.

I wonder if we should have some support for loading the CSS via javascript. I don't think we'd want it to always be the case, and I don't have a great idea about how to configure it, but I thought I'd log it.

Of course, #38 is a different way of addressing this issue, and maybe a nicer one.

**Comment by duner** [comment]
Closing this now that we're using the iframe stuff.
