### ISSUE TITLE
Invalid URLs

### ISSUE THREAD

**Issue by jordyndahl** [NUKnightLab/juxtapose#45]
I'm trying to make a slider using two photos of pollution in China that I recently took, but every time I put the links in, the preview goes blank/white and won't show up. I saw a post in this forum that the preview goes blank when the URL's are invalid. I've tried using links from Dropbox and Google Drive. Has anyone else had this problem and do you have a solution?

These are the links I've tried to use:
https://www.dropbox.com/s/2zhpglr1md3sbj4/JS_Clear.JPG
https://www.dropbox.com/s/znaddf7hn5aqsrd/JS_Pollution.JPG
https://drive.google.com/file/d/0B36zihP_tLchUEFIQi1oNlpqT2c/view
https://drive.google.com/file/d/0B36zihP_tLchbDF3bUgxcTRBb0k/view

**Comment by JoeGermuska** [comment]
Please use knightlab.zendesk.com for support questions.

The specific answer to this question: https://knightlab.zendesk.com/entries/81268849-Using-Dropbox-images-on-JuxtaposeJS

We recommend against trying to use Google Drive for image hosting. In the past, URLs which worked suddenly stopped working. It doesn't seem that Google considers that a supported feature of Drive.
