### ISSUE TITLE
Does JuxtaposeJS work on Wordpress.com?

### ISSUE THREAD

**Issue by Janysach** [NUKnightLab/juxtapose#46]
Hi.  I am trying to add a juxtapose to  a blog post in Wordpress.com as the instructions say in the page, but it would not work. Is the slider made to work in these blog pages?

**Comment by peejayw** [comment]
Not for me :-(

**Comment by knightlab** [comment]
Please see https://knightlab.zendesk.com/entries/80698589-Can-I-use-JuxtaposeJS-on-Wordpress-

We're working on a revised model for JuxtaposeJS embeds which will work around this issue.
