### ISSUE TITLE
SALT deployment of new codebase

### ISSUE THREAD

**Issue by thejordan** [NUKnightLab/juxtapose#47]
We can discuss this with @scott2b when he's done with his current round at Ford

**Comment by JoeGermuska** [comment]
at this time, the staging version of the site does not write the requisite JSON to S3, so the embeds do not work

**Comment by scott2b** [comment]
I am unfamiliar with the code. Is this some deployment/configuration/environment issue, or is it that the code does not work as expected?

**Comment by JoeGermuska** [comment]
the code doesn't work as expected. Probably because of a configuration/environment issue. @duner is out of town. Maybe he can help us dial in on the issue when he gets back and before he leaves again; otherwise, one of us will have to sleuth through the code.

**Comment by JoeGermuska** [comment]
my bad. the files are being created on S3. the problem is that they are created in a "staging" bucket, but the Juxtapose JS code assumes they should be loaded from the "production" bucket.
