### ISSUE TITLE
Update keyboard a11y to account for inline images? 

### ISSUE THREAD

**Issue by radiocontrolled** [NUKnightLab/juxtapose#52]
Hi Alex, as juxtapose now has inline images, would you be interested in a pull request to update keyboard a11y to take this into consideration? I would update my fork @ https://github.com/radiocontrolled/juxtapose

**Comment by duner** [comment]
That would be great! Could you update your fork and then submit a pull
request?

On Mon, Jun 15, 2015 at 4:35 PM, Alison Benjamin <notifications@github.com>
wrote:

> Hi Alex, as juxtapose now has inline images, would you be interested in a
> pull request to update keyboard a11y to take this into consideration? I
> would update my fork @ https://github.com/radiocontrolled/juxtapose
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NUKnightLab/juxtapose/issues/52>.
>



-- 
duner.me
@asduner <http://twitter.com/asduner>

**Comment by radiocontrolled** [comment]
Yes, I will do. Though I'm having some fabric problems - I'm unable to serve the development website: 

http://stackoverflow.com/questions/30956852/cant-serve-a-site-with-fabric-but-fabric-is-installed

Any insight into this?

**Comment by jywsn** [comment]
@radiocontrolled What is the output when you run `fab -l` in Terminal?

**Comment by jywsn** [comment]
I can confirm that `fab serve` does not work (although I have a different problem than radiocontrolled):
```
Notice: Loaded config @ /Users/jenny/repos/juxtapose/config.json

[localhost] local: python website/app.py -p 5000
Traceback (most recent call last):
  File "website/app.py", line 22, in <module>
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (settings_module, e))
ImportError: Could not import settings 'core.settings.loc' (Is it on sys.path?): No module named secrets

Fatal error: local() encountered an error (return code 1) while executing 'python website/app.py -p 5000'

Aborting.
```

**Comment by jywsn** [comment]
Also running `python website/app.py` does not work:

```
Traceback (most recent call last):
  File "website/app.py", line 22, in <module>
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (settings_module, e))
ImportError: Could not import settings 'core.settings.loc' (Is it on sys.path?): No module named secrets
```

**Comment by jywsn** [comment]
Moving the last two comments into a separate bug report...

**Comment by JoeGermuska** [comment]
closing, obsoleted by #81 and also #53
