### ISSUE TITLE
Cannot run development server

### ISSUE THREAD

**Issue by jywsn** [NUKnightLab/juxtapose#53]
(ref https://github.com/NUKnightLab/juxtapose/issues/52)

`fab serve` does not work:
```
Notice: Loaded config @ /Users/jenny/repos/juxtapose/config.json

[localhost] local: python website/app.py -p 5000
Traceback (most recent call last):
  File "website/app.py", line 22, in <module>
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (settings_module, e))
ImportError: Could not import settings 'core.settings.loc' (Is it on sys.path?): No module named secrets

Fatal error: local() encountered an error (return code 1) while executing 'python website/app.py -p 5000'

Aborting.
```

Also running `python website/app.py` does not work:

```
Traceback (most recent call last):
  File "website/app.py", line 22, in <module>
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (settings_module, e))
ImportError: Could not import settings 'core.settings.loc' (Is it on sys.path?): No module named secrets
```

**Comment by radiocontrolled** [comment]
jqwysn, <code>fab -l</code> gives me this: 

Available commands:

    abspath                 Return an absolute path.
    add_paths               Make paths are in sys.path.
    basename                Returns the final component of a pathname
    chown                   User sudo to set user and group ownership
    chput                   Put file and set user and group ownership.  Default to use sudo.
    contextmanager          @contextmanager decorator.
    cron                    Create entry in /etc/cron.d
    debconf_set_selections  Given package and map config:(type,value), set selections
    default_roles           Decorate task with these roles by default, but override with -R, -H
    diff                    Return true if local and remote paths differ in contents
    dirname                 Returns the directory component of a pathname
    hasrole                 True if current host has the specified role
    hostroles               Iterate over role that are in both env.roles and the
    install_deb             Install package from custom deb hosted on S3.
    join                    Join two or more pathname components, inserting '/' as needed.
    make_version            Build git version string for current directory
    md5sum                  Return md5sum of remote file
    mkdir                   Create directory with sudo and octal mode, then set ownership.
    package_ensure_apt      Ensure apt packages are installed
    package_install_apt
    package_update_apt
    package_upgrade_apt
    pickrole                Return first of role_list (or env.roles) valid for current host.
    rsync                   Helper to rsync submodules across
    splunk                  Authenticated call to splunk
    splunk_monitor          Monitor a list of (path, sourcetype) pairs in splunk
    tagversion              (repo,level=patch,special='') Levels are major,minor,patch
    tempput                 Put a file to remote and remove it afterwards
    update_apt              Update apt index if not update in last N days
    watch                   Call callback if any of filenames change during the context
    write_version           Update version file using git desribe

**Comment by jywsn** [comment]
So... this doesn't look anything like our available fabric commands.  I read your stackoverflow post (http://stackoverflow.com/questions/30956852/cant-serve-a-site-with-fabric-but-fabric-is-installed).  I just want to verify that your cloned *our* fablib repository (https://github.com/NUKnightLab/fablib) into the same parent directory as your juxtapose repository.  

There is a pip installable library named fablib that has nothing to do with juxtapose.  If you installed that globally or in your virtualenv, you may be experiencing issues related to that.

**Comment by radiocontrolled** [comment]
Hey, a few things. So it looks like I did have a fablib within my virtualenv. I did <code> pip uninstal fablib </code> within my juxtapose directory, and now my list of available commands matches yours: 


    branch        Specify a branch other than master
    build         Build version
    debug         Setup debug settings to test deployment
    deploy        Deploy website to S3 bucket.  Specify stg|prd as argument.
    dump          Dump env and config (if applicable) to stdout
    put           Put (copy) website to S3 bucket.  Specify stg|prd as argument.
    render        Render templates (deploy except for actual sync with S3)
    serve         Run the development server
    stage         Build/commit/tag/push version, copy to local cdn repository
    stage_dev     Build and copy to local cdn repository as 'dev' version
    stage_latest  Copy version to latest within local cdn repository
    undeploy      Delete website from S3 bucket.  Specify stg|prd as argument.
    untag         Delete a tag (in case of error)

When I run <code>fab serve</code> I get this result: 


    Warning: Could not find 's3cmd.cfg' repository at '/Applications/MAMP/htdocs/secrets/s3cmd.cfg'.  You will not be able to deploy.
    Notice: Loaded config @ /Applications/MAMP/htdocs/juxtapose/config.json
    [localhost] local: python website/app.py -p 5000
    Traceback (most recent call last):
    File "website/app.py", line 22, in <module> raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (settings_module, e))
    ImportError: Could not import settings 'core.settings.loc' (Is it on sys.path?): No module named secrets

    Fatal error: local() encountered an error (return code 1) while executing 'python website/app.py -p 5000'

    Aborting.

I think I need secrets - but I don't have the access rights to that repo. 
I think fablib is in the same parent directory, or am I missing something? 
htdocs/fablib 
htdocs/juxtapose

thanks

**Comment by jywsn** [comment]
You are setup fine.  This is an error in the juxtapose configuration.

**Comment by radiocontrolled** [comment]
Ok, I'm not sure how to fix the juxtapose configuration so I'll watch this thread for a fix. Thank you. Alison

**Comment by radiocontrolled** [comment]
hi jywsn, any update on this? I'd like to work on a pull request but need help setting up the development environment to do so. thanks, Alison

**Comment by JoeGermuska** [comment]
@radiocontrolled Thanks for your interest. To be honest, running the local server is pretty entangled with stuff we can't put in github, because the server exists just to push data to Amazon S3 so that we can support iframe embeds.

From a quick look, all of your changes are in javascript, right? And you even have a test page. Maybe we should forgo trying to get the server running in favor of being able to include your contribution?

If there's a reason I'm missing (besides "correctness") that you need to run the local server, let us know...

**Comment by radiocontrolled** [comment]
Oh I didn't realise that. Ok, with the test page I made a small pull request to fix left/right on the handle again. I wanted to run the local server to work on website/static/js/main.js and website/static/templates/main.js_create.html (at least I think those are the files) to play with adding alt text to slider creation.
