### ISSUE TITLE
facilitate sizing the juxtapose?

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/juxtapose#54]
Today I've seen two Zendesk tickets from people who don't know how to control the size of the iframe. Maybe we should help.

Idea: use JS to read the dimensions of the first image and use that to add width/height attributes to the iframe? Open to other ideas.

**Comment by JoeGermuska** [comment]
Continuing to get issues from folks about this. With no other input, I'm going to say we should go ahead and make this something we do for people in the form.

I'm inclined to just set it automatically in the iframe based on the dimensions of the given images (probably whichever is smaller if they don't match?) Exposing input fields for width and height adds the complexity of figuring out if people have overridden the values, and with letting people switch between "inferred" and "explicit". I think for now if people want to override they can manually edit the `iframe` markup.

**Comment by duner** [comment]
This seems reasonable to me @JoeGermuska. I'd take a look at these two functions https://github.com/NUKnightLab/juxtapose/blob/master/juxtapose/js/juxtapose.js#L92-L109 from the main Juxtapose file which could probably be used in the admin code to set those variables.

**Comment by JoeGermuska** [comment]
From twitter, an example of the default iframe behaving "unexpectedly" http://www.shortlist.com/cool-stuff/to-do-list/test-slider vs timelines made with the "JS scans the page for markup" version http://www.shortlist.com/entertainment/music/then-now-glastonbury-festival-1971-2015
