### ISSUE TITLE
Allow user to specify whether width or height should be used for sizing

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/juxtapose#62]
Currently the javascript uses the width of the smaller image + the image ratio to create the iframe and preview. It's conceivable that someone might want to instead control for height. We should add an option to the panel that allows either width or height to be specified and used in the calculations. (But we should not allow both to be set at once -- I'm picturing a dropdown that forces the user to specify which is being given preference.)

**Comment by duner** [comment]
This is no longer an issue now, right @hbillings? I'm going to go ahead and close it.

**Comment by oompt** [comment]
Just curious: why this is no longer an issue?

I'm using Juxapose on a page with a bunch of comparisons, four of which are side-by-side. The pictures being compared are all exactly the same dimensions; however, in running Juxapose the heights of the pictures are calculation at slightly (within a couple pixels) different heights.

I think an elegant-enough solution would be some kind of ``mode: responsive`` option where the static dimension calculations are turned off, and you just do a basic 'width: 100%; height: auto;' type of configuration on the CSS.  

The reasoning here is that Juxapose can be dropped into a responsive grid where the CSS can do the bulk of the work. This should be more performant in instances where a lot of comparisons are being made. 

Does such a thing exist? I looked around but didn't find anything.

**Comment by oompt** [comment]
I see now that the responsive option is only for the iframe container. Hmm. Would love responsive image containers too. I took a shot at hacking the source; I'll push a commit if it works out. So far, no luck.

**Comment by hbillings** [comment]
@oompt: I'm not completely certain that I get what you're asking about, so I'll try to give you a sensible answer, but apologies in advance if this doesn't answer your questions. Yes, the responsive option is specifically for the iframe. That's there to handle the fact that iframes don't fundamentally know the height of their contents, so without that functionality, content can get clipped or sized oddly. I'm not sure how divs (which is what I think you mean by "responsive image containers"?) would benefit from the same sort of handling. (Also, note that while not responsive in the sense that it checks for `window.onresize`, Juxtapose does recalculate the size of its container on page reload.)

**Comment by duner** [comment]
(also Juxtapose does have a `window.onresize` event listener, so if you are using it outside of an iFrame, it should be always be set to 100% of the width of its container https://github.com/NUKnightLab/juxtapose/blob/master/juxtapose/js/juxtapose.js#L528-L530)

**Comment by hbillings** [comment]
@duner well hey so it does! Filing a ticket to fix the example juxtapose. :)

**Comment by oompt** [comment]
@hbillings @duner 

I guess all I'm asking is whether the comparison effect can be achieved without explicitly setting dimensions on the (image) containers. The ``window.onresize`` function doesn't work for my purposes—for example it won't resize back up after going down, and the initial sizing seems to get a bit messed up with you stack container horizontally anyway. Check this out. These pictures are all the same size: 

![example](http://f.cl.ly/items/2y0B1k0G411B3o2S2b1F/Image%202015-10-02%20at%2011.54.09%20AM.png)

However, if you could set the css to ``width: 100%; height: auto``, and still maintain the comparison effect, that would be nice. I played around around with a percentage-based approach yesterday for a while, but couldn't crack it.

**Comment by oompt** [comment]
Definitely a hack, but this works for my purposes.

![the picture](http://f.cl.ly/items/0x1Q0I2x1T2v0k1n3r0G/Image%202015-10-05%20at%2011.32.00%20AM.png)
