### ISSUE TITLE
left image not visible in iOS Safari

### ISSUE THREAD

**Issue by ryanpitts** [NUKnightLab/juxtapose#63]
So this is a weird one: We ran into an issue where the left image in the slider was not visible on mobile safari. 

![screen shot 2015-07-23 at 12 13 49 pm](https://cloud.githubusercontent.com/assets/56477/8859779/53f9788e-3134-11e5-887a-c221c87e697c.png)

I was able to fix the problem by overriding this line of Juxtapose's CSS:

    div.jx-image {
        -webkit-transform: scale(1);
    }

Changing this to `-webkit-transform: none` made the image visible and the juxtapose behaved as expected. I'm not sure why that scale() is in there, or for that matter why removing it corrected the issue.

Our particular implementation was definitely non-standard.

* Our content exists inside a fixed div with scrolling enabled to allow for a sliding nav pane. Originally I thought the problem might be related to the parenting of an absolutely positioned juxtapose image.
* We could not use iframe embeds because their sizing was not responsive to browser width. We triggered the juxtaposes on our page manually, invoking the guts of your iframe with some custom js.

It may be that we are just a weird use case, but it also may be worth checking things in mobile Safari and seeing if this is a persistent issue, and/or whether the scale() is important to keep.

**Comment by JoeGermuska** [comment]
@duner can you explain why we need the transform?

**Comment by duner** [comment]
If I recall correctly, that was part of the solution to #4 and was first introduced in ed9c84b9093996ac679c375a981bb6da229bbb58. But I'm not sure if that's still needed or if the rounding was sufficient to solve that problem. I should have some time this week to test if we can get rid of it or not.

**Comment by ryanpitts** [comment]
hooray for deleting LOC!
