### ISSUE TITLE
Event to animate slider to start position

### ISSUE THREAD

**Issue by duner** [NUKnightLab/juxtapose#66]
From #56, via @kirkman:

>Would you consider adding an option to animate the slider gliding to its start position from the left side, onload? Here's an old example of what I'm trying to describe: http://images.stltoday.com/mds/00003582/content/index.html

**Comment by Kirkman** [comment]
For whatever it's worth, I ended up achieving this effect by [simulating a click](http://marcgrabanski.com/simulating-mouse-click-events-in-javascript/) in the middle of the slider. 

I'm sure this is not how you would want to do it in your code, but here's what I added to your _init function (I also included the JS click simulator above):

````
	// Find width/height
	var photoWidth = document.getElementById('juxtapose-wrapper').offsetWidth;
	var photoHeight = document.getElementById('juxtapose-wrapper').offsetHeight;

	// Calculate target coordinates for middle of the interactive
	var targetX = parseInt((photoWidth + 40) / 2);
	var targetY = parseInt(photoHeight / 2);

	// Create our simulated mousedown event
	var eventDown = mouseEvent("mousedown", targetX, targetY, targetX, targetY);
	var eventUp = mouseEvent("mouseup", targetX, targetY, targetX, targetY);

	// Send the event to this.slider
	dispatchEvent(this.slider, eventDown);
	// Send the event to this.slider
	dispatchEvent(this.slider, eventUp);
````

Example here: http://graphics.stltoday.com/apps/ferguson-then-now/slider-3.html

**Comment by duner** [comment]
A few thoughts on figuring out a good way to do this. Every JXSlider already has a `updatePosition` method that can be called instead of simulating the click like you did (though that's an admittedly nifty solution and we should probably update our documentation to make this option more clear). 

Would it make sense to have the handle animate to it's starting positing on load or when the slider comes into the viewport? Should this be the default behavior — I'm concerned about adding too many options into Juxtapose?

**Comment by duner** [comment]
I don't think there's a smart way to implement this in the default iFrame version of Juxtapose (ie. there's no way to know when the Juxtapose enters the viewport. So I think we are going to go ahead and skip adding this as an option.

There's probably a great way to implement something using the callback and the `updatePosition` function — and we'll work on better documentation (including Tips and Tricks which can include something like this).
