### ISSUE TITLE
Convert dropbox embedded image page URLs to direct image links

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/juxtapose#67]
As with #64, this is probably better handled in the authoring tool rather than create a special Image subclass.

Given a URL like
`https://www.dropbox.com/s/yuy2dxj6pxz9jf8/cole.jpg?dl=0`
convert the domain in the URL as such:
`https://dl.dropboxusercontent.com/s/yuy2dxj6pxz9jf8/cole.jpg?dl=0`

**Comment by duner** [comment]
We could do that. Another thought I've had for the Dropbox part is to
enable their "chooser" code which can return the direct link to a file and
also is maybe a better UI?
https://www.dropbox.com/developers/dropins/chooser/js

On Wed, Aug 19, 2015 at 6:54 PM, Joe Germuska <notifications@github.com>
wrote:

> As with #64 <https://github.com/NUKnightLab/juxtapose/issues/64>, this is
> probably better handled in the authoring tool rather than create a special
> Image subclass.
>
> Given a URL like
> https://www.dropbox.com/s/yuy2dxj6pxz9jf8/cole.jpg?dl=0
> convert the domain in the URL as such:
> https://dl.dropboxusercontent.com/s/yuy2dxj6pxz9jf8/cole.jpg?dl=0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NUKnightLab/juxtapose/issues/67>.
>



-- 
duner.me
@asduner <http://twitter.com/asduner>

**Comment by JoeGermuska** [comment]
Let's do the simple thing now, and if we want to add the chooser parts, that can be a separate issue/initiative
