### ISSUE TITLE
Github page example code issue

### ISSUE THREAD

**Issue by zzolo** [NUKnightLab/juxtapose#72]
Hey all.  Great project.

Was just getting this up and running locally and noticed that the example in the README (Github page) is not correct.  It has the following code:

```
<div id="foo"></div>
<script>
slider = new JXSlider('#foo', 
```

When it should have:

```
<div id="foo"></div>
<script>
slider = new juxtapose.JXSlider('#foo', 
```

**Comment by JoeGermuska** [comment]
Thank you, sir!
