### ISSUE TITLE
Allow responsivizeIframe 

### ISSUE THREAD

**Issue by zzolo** [NUKnightLab/juxtapose#73]
I don't have a full view of how Juxtapose works exactly, but when trying to get this to work nicely with iframes and specifically Pym.js, I had to remove the `responsivizeIframe` call while manually setting the size of the container.

So, it would be nice to make the iframe handling optional since its pretty opinionated.

**Comment by duner** [comment]
I think it still makes sense to leave the default juxtapose-in-iframe behavior use the responsiveIframe method. But we can incorporate an option that disables it I think. I'll probably tackle this after dinner @hbillings.

**Comment by hbillings** [comment]
It makes sense that this wouldn't work with Pym.js, but the default juxtapose generator at juxtapose.knightlab.com needs a built-in option to responsivize the iframe.

**Comment by zzolo** [comment]
Whoa, that was quick!  Awesome.  Yeah, definitely thought it should be an option and on by default.
