### ISSUE TITLE
Same Sized Pictures Displaying at Different Dimensions

### ISSUE THREAD

**Issue by oompt** [NUKnightLab/juxtapose#78]
All these pictures are the exact same dimensions, but Juxtapose is applying slightly different heights to them. Any help with this would be appreciated. 

![the picture](http://f.cl.ly/items/2y0B1k0G411B3o2S2b1F/Image%202015-10-02%20at%2011.54.09%20AM.png)

**Comment by hbillings** [comment]
A link to an example of this would be very helpful.

**Comment by oompt** [comment]
Sorry this was my mistake. Pictures are sizing appropriately now.
