### ISSUE TITLE
juxtapose and Facebook

### ISSUE THREAD

**Issue by chinocudeiro** [NUKnightLab/juxtapose#94]
Hi! Thaks for your job.

I create a lot of juxtapose slides, but, I like post this slides on Facebook. I only can publish like a link, but I prefer publish directly, like videos and photos, and you can use the slide directly on facebook wall or group.

Can you help me? Thanks

**Comment by duner** [comment]
Hi @chinocudeiro — Thanks for using Juxtapose! Right now Facebook doesn't support a way for us to embed interactive sliders on walls or in groups. Sadly, that's just one of the limitations Facebook imposes on us all. 

Sorry for the delayed reply to your query; we generally are quicker to respond on [Zendesk](https://knightlab.zendesk.com/hc/en-us), which is our primary support platform.
